#!/bin/bash

# Configuration path
CONFIG_PATH="/etc/deadmansw/deadmansw.conf"

# Extract configurations
MONITORED_USER=$(grep "MONITORED_USER" $CONFIG_PATH | cut -d'=' -f2 | tr -d '"')

# Extracting time configurations and converting them to integers for arithmetic operations
TIME_MINUTES=$(grep "TIME_MINUTES" $CONFIG_PATH | cut -d'=' -f2 | tr -d '"' | bc)
TIME_HOURS=$(grep "TIME_HOURS" $CONFIG_PATH | cut -d'=' -f2 | tr -d '"' | bc)
TIME_DAYS=$(grep "TIME_DAYS" $CONFIG_PATH | cut -d'=' -f2 | tr -d '"' | bc)
TIME_WEEKS=$(grep "TIME_WEEKS" $CONFIG_PATH | cut -d'=' -f2 | tr -d '"' | bc)
TIME_MONTHS=$(grep "TIME_MONTHS" $CONFIG_PATH | cut -d'=' -f2 | tr -d '"' | bc)

# Calculate the inactivity time in seconds based on all the specified time parameters
INACTIVITY_SECONDS=$(( 
    TIME_MINUTES * 60 +
    TIME_HOURS * 3600 +
    TIME_DAYS * 86400 +
    TIME_WEEKS * 604800 + 
    TIME_MONTHS * 2592000 
))

# Get the last login time for the MONITORED_USER
last_login=$(last -n 1 $MONITORED_USER | head -n 1 | awk '{print $4, $5, $6, $7}')

# Convert it to a timestamp for comparison
last_login_timestamp=$(date --date="$last_login" +%s)
current_timestamp=$(date +%s)

# Calculate difference
time_difference=$((current_timestamp - last_login_timestamp))
time_remaining=$((INACTIVITY_SECONDS - time_difference))

# Display remaining time
if [ "$time_remaining" -le 0 ]; then
    echo "Deletion timer has passed. Shredding process has either completed or the activity timer will restart on the next service start"
else
    days=$((time_remaining / 86400))
    hours=$(( (time_remaining % 86400) / 3600))
    mins=$(((time_remaining % 3600) / 60))
    secs=$((time_remaining % 60))
    echo "Time remaining until shredding: $days days, $hours hours, $mins minutes, $secs seconds."
fi
